export const GET_BANDS = 'GET_BANDS';
export const GET_GENRE = 'GET_GENRE';
export const GET_ALBUMS = 'GET_ALBUMS';
export const SELECTED_BAND = 'SELECTED_BAND';
export const SELECTED_BAND_GENRE = 'SELECTED_BAND_GENRE';
export const SELECTED_BAND_MEMBERS = 'SELECTED_BAND_MEMBERS';
export const CHANGE_PAGE = 'CHANGE_PAGE';
export const CONDITIONAL_RENDERING = 'CONDITIONAL_RENDERING';
